//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Appli_CocoriCO2.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.1")]
        public string MasterIPAddress {
            get {
                return ((string)(this["MasterIPAddress"]));
            }
            set {
                this["MasterIPAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int dataQueryInterval {
            get {
                return ((int)(this["dataQueryInterval"]));
            }
            set {
                this["dataQueryInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string dataLogInterval {
            get {
                return ((string)(this["dataLogInterval"]));
            }
            set {
                this["dataLogInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:/CocoriCO2/CocoriCO2_CRCBN")]
        public string dataFileBasePath {
            get {
                return ((string)(this["dataFileBasePath"]));
            }
            set {
                this["dataFileBasePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cocorico2")]
        public string ftpUsername {
            get {
                return ((string)(this["ftpUsername"]));
            }
            set {
                this["ftpUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C0q2Ch0c@2021")]
        public string ftpPassword {
            get {
                return ((string)(this["ftpPassword"]));
            }
            set {
                this["ftpPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp.obs-vlfr.fr/CRCBN/")]
        public string ftpDir {
            get {
                return ((string)(this["ftpDir"]));
            }
            set {
                this["ftpDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8086/orgs/de9be6257a0a3477/dashboards/077b31f0db0d2000?lower=now" +
            "%28%29%20-%207d")]
        public string InfluxDBWebpage {
            get {
                return ((string)(this["InfluxDBWebpage"]));
            }
            set {
                this["InfluxDBWebpage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("eUNDgxqrwAFsb6pjOdqGkW-Qr9NxorO5WQamvvgtquXFJgUz1tyG2Ee-G7HhI_IKk9L3JavnAoxrMZ5ev" +
            "Ls9Ig==")]
        public string InfluxDBToken {
            get {
                return ((string)(this["InfluxDBToken"]));
            }
            set {
                this["InfluxDBToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CocoriCO2")]
        public string InfluxDBBucket {
            get {
                return ((string)(this["InfluxDBBucket"]));
            }
            set {
                this["InfluxDBBucket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CNRS")]
        public string InfluxDBOrg {
            get {
                return ((string)(this["InfluxDBOrg"]));
            }
            set {
                this["InfluxDBOrg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.obs-vlfr.fr/~gazeau/FACE-IT/FACE-IT.html")]
        public string RDataWebpage {
            get {
                return ((string)(this["RDataWebpage"]));
            }
            set {
                this["RDataWebpage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FluoSlope {
            get {
                return ((string)(this["FluoSlope"]));
            }
            set {
                this["FluoSlope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FluoOffset {
            get {
                return ((string)(this["FluoOffset"]));
            }
            set {
                this["FluoOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xapp-1-A02GU516K6E-2572202941058-01eb87f248250644435edd81f5b5d13c6401ae0a930b1f91" +
            "631d4ce6718223b9")]
        public string SlackToken {
            get {
                return ((string)(this["SlackToken"]));
            }
            set {
                this["SlackToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CRCM")]
        public string SlackChannelID {
            get {
                return ((string)(this["SlackChannelID"]));
            }
            set {
                this["SlackChannelID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmLevelH {
            get {
                return ((bool)(this["AlarmLevelH"]));
            }
            set {
                this["AlarmLevelH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmLevelL {
            get {
                return ((bool)(this["AlarmLevelL"]));
            }
            set {
                this["AlarmLevelL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmLevelLL {
            get {
                return ((bool)(this["AlarmLevelLL"]));
            }
            set {
                this["AlarmLevelLL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmPressure {
            get {
                return ((bool)(this["AlarmPressure"]));
            }
            set {
                this["AlarmPressure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmpHCondition {
            get {
                return ((bool)(this["AlarmpHCondition"]));
            }
            set {
                this["AlarmpHCondition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmTempCondition {
            get {
                return ((bool)(this["AlarmTempCondition"]));
            }
            set {
                this["AlarmTempCondition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmFlowrate {
            get {
                return ((bool)(this["AlarmFlowrate"]));
            }
            set {
                this["AlarmFlowrate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmpHMesocosm {
            get {
                return ((bool)(this["AlarmpHMesocosm"]));
            }
            set {
                this["AlarmpHMesocosm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlarmTempMesocosm {
            get {
                return ((bool)(this["AlarmTempMesocosm"]));
            }
            set {
                this["AlarmTempMesocosm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PressureDelta {
            get {
                return ((string)(this["PressureDelta"]));
            }
            set {
                this["PressureDelta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlowrateDelta {
            get {
                return ((string)(this["FlowrateDelta"]));
            }
            set {
                this["FlowrateDelta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FlowrateSetpoint {
            get {
                return ((string)(this["FlowrateSetpoint"]));
            }
            set {
                this["FlowrateSetpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionpHDelta {
            get {
                return ((string)(this["ConditionpHDelta"]));
            }
            set {
                this["ConditionpHDelta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConditionTempDelta {
            get {
                return ((string)(this["ConditionTempDelta"]));
            }
            set {
                this["ConditionTempDelta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MesocosmpHDelta {
            get {
                return ((string)(this["MesocosmpHDelta"]));
            }
            set {
                this["MesocosmpHDelta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MesocosmTempDelta {
            get {
                return ((string)(this["MesocosmTempDelta"]));
            }
            set {
                this["MesocosmTempDelta"] = value;
            }
        }
    }
}
